Repository Resourcio-Community/Resourcio_Community-Website, pull requests merged in 2023-07, with the labels that each got.

#285 added changes in progress scrollbar
  frontend/src/App.css
  frontend/src/scenes/home/Home.jsx
  frontend/src/scenes/resources/Resources.jsx
Labels: level2, gssoc23

#291 Added darkmode to the website.
  frontend/package-lock.json
  frontend/src/component/faq/FAQ.jsx
  frontend/src/component/navbar/Navbar.jsx
  frontend/src/component/navbar/navbar.css
  frontend/src/component/team/index.jsx
  frontend/src/component/themeChange/ThemeButton.jsx
  frontend/src/context/ThemeContext.js
  frontend/src/scenes/home/Home.jsx
Labels: level3, gssoc23

#295 Added hover effect on socials
  frontend/package-lock.json
  frontend/src/component/footer/footer.css
Labels: level1, gssoc23

#302 Resources page design fixed.
  frontend/src/component/resourceCard/ResourceCard.jsx
  frontend/src/component/resourceCard/resourceCard.css
  frontend/src/scenes/resources/Resources.jsx
  frontend/src/scenes/resources/resources.css
Labels: level3, gssoc23

#301 navbar redesign
  frontend/src/component/navbar/Navbar.jsx
  frontend/src/component/navbar/navbar.css
Labels: level2, gssoc23

#314 Added user name display and logout option on HomePage after login
  frontend/package-lock.json
  frontend/src/Images/logout.png
  frontend/src/component/navbar/Navbar.jsx
  frontend/src/component/navbar/navbar.css
  frontend/src/component/profile/Profile.jsx
  frontend/src/component/profile/profile.css
  server/controllers/authControllers.js
Labels: level2, gssoc23

#318 carousel added to the team page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/component/team/index.jsx
Labels: level2, gssoc23

#319 Redesign Footer
  frontend/src/component/footer/Footer.jsx
  frontend/src/component/footer/footer.css
Labels: level3, gssoc23
