Repository Resourcio-Community/Resourcio_Community-Website, pull requests merged in 2023-06, with the labels that each got.

#171 Changed login and signup color scheme
  frontend/src/scenes/login/login.css
Labels: level2, gssoc23

#174 Update README.md
  README.md
Labels: level1, gssoc23

#169 Suggested Style Changed
  frontend/package.json
  frontend/src/component/stats/Stat.jsx
  frontend/src/component/stats/stat.css
  frontend/src/scenes/home/Home.jsx
Labels: level2, gssoc23

#181 Added Pull Request Template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: level1, gssoc23

#185 addition of sitemap
  frontend/public/robots.txt
  frontend/public/sitemap.xml
Labels: level3, gssoc23

#187 Update index.html
  frontend/public/index.html
Labels: level1, gssoc23

#192 added the scroll button in resources page
  frontend/src/scenes/resources/Resources.jsx
Labels: level2, gssoc23

#190 feat: team component
  frontend/package.json
  frontend/src/component/footer/Footer.jsx
  frontend/src/component/navbar/Navbar.jsx
  frontend/src/component/team/team.jsx
  frontend/src/scenes/home/Home.jsx
  server/package-lock.json
Labels: level3, gssoc23

#216 Alt attributes added
  frontend/src/component/category/Category.jsx
  frontend/src/component/contactCard/ContactCard.jsx
  frontend/src/component/footer/Footer.jsx
  frontend/src/component/loadingScreen/LoadingScreen.jsx
  frontend/src/component/navbar/Navbar.jsx
  frontend/src/scenes/home/Home.jsx
Labels: level1, gssoc23

#246 Added codeql workflow - github action
  .github/workflows/codeql.yml
Labels: level1, gssoc23

#266 Resolved Issue #219 : Added flip effects in cards
  frontend/src/component/category/Category.jsx
  frontend/src/component/category/category.css
  frontend/src/scenes/home/home.css
Labels: level2, gssoc23

#271 Eye toggle
  frontend/src/scenes/login/Login.jsx
Labels: level1, gssoc23

#268 Resolved #219 : responsiveness issue in flip cards
  frontend/src/scenes/home/Home.jsx
  frontend/src/scenes/home/home.css
Labels: level2, gssoc23

#283 Faq section
  frontend/.gitignore
  frontend/package-lock.json
  frontend/src/component/faq/data/index.jsx
  frontend/src/component/faq/index.jsx
  frontend/src/component/faq/styles/index.jsx
  frontend/src/scenes/home/Home.jsx
  server/.gitignore
Labels: level3, gssoc23
